### ISSUE TITLE
 Helm chart should allow users to pass in config via values.yaml

### ISSUE THREAD

**Issue by javydekoning** [openspeedtest/Helm-chart#2]
Use of ingress (a reverse proxy) is common in the k8s world. 

By default, this breaks upload monitoring. From your docs I understand that:

- Warning! If you run it behind a **[Reverse Proxy](https://github.com/openspeedtest/Speed-Test/issues/4#issuecomment-1229157193)**, you should increase the `post-body content length` to 35 megabytes.

https://github.com/openspeedtest/Docker-Image/blob/main/README.md?plain=1#L32

But the helm chart does not allow me to pass in a configuration file (via [configMap](https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/) ).

**Comment by openspeedtest** [comment]
https://github.com/openspeedtest/Speed-Test/issues/31#issuecomment-1235671004 Can you send a PR?

**Comment by javydekoning** [comment]
Thank for that link. I didn't know this was a proxy setting. Based on that, perhaps it's best to add it just as a commented out line in the annotations object of the Ingress. 

Given that this setting is not standardized between ingress controllers, we can't standardize it in the helm template.

I can submit a PR.
